# Generated by Django 2.1 on 2019-07-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pokemon',
            table='Pokemons',
        ),
    ]
